### ISSUE TITLE
what if I don't use it as a joke

### ISSUE THREAD

**Issue by PH-KDX** [vcokltfre/yamlimg#1]
Will you provide technical support if I use this in production code?
On that note, are you open to a collaboration with tidelift to reduce dependency uncertainty?

**Comment by vcokltfre** [comment]
Support for production usage is not provided, except by prior arrangement after a large sum of money has been paid to me.

**Comment by PH-KDX** [comment]
What sum of money are you considering, and in which currency?
May I pay it in Knuts, Sickles and Galleons? I've always found the idea of using fantastical currency to pay for fantastic work quite appealing.

**Comment by vcokltfre** [comment]
Approximately 7 metric tonnes of Monopoly 500 paper money, along with 19 seagull statues and the soul of an unborn child.

**Comment by PH-KDX** [comment]
Does the weight of the soul matter? If so, please specify in stones, grains and ounces.
Also, could you define a metric tonne? I know of an Imperial tonne, and a metric ton, but I have never heard of a metric tonne.

**Comment by vcokltfre** [comment]
The weight of the soul is 4 kilograms and 3 ounces.
Metric tonne: halfway between a metric ton and an imperial tonne.

**Comment by PH-KDX** [comment]
Alright, how would you like it dispatched?
I can organise shipping via either broomstick-drawn chariots or flying carpets. Reindeer sleds are unfortunately exclusively a Yuletide service.

**Comment by vcokltfre** [comment]
Each piece of Monopoly money should be delivered by an individual carrier pigeon. The seagull statues should be flown by seagulls for true authenticity, and the soul of the unborn child should be transported via jetpack to ensure timely delivery.

**Comment by DavinderJolly** [comment]
___________________
< can ducks use it? >
 -------------------
 \
  \
   \ >()_
      (__)__ _

**Comment by PH-KDX** [comment]
> Each piece of Monopoly money should be delivered by an individual carrier pigeon.

You'll have to deliver the carrier pigeons, then, or they won't fly to you and I'll be stuck with an obscene amount of carrier pigeons and their produce.
> The seagull statues should be flown by seagulls for true authenticity 

Like James and the Giant Peach?
> the soul of the unborn child should be transported via jetpack

How do you suggest I prevent it evaporating in the strong wind? You probably have more experience with this than I do.

**Comment by DavinderJolly** [comment]
```
 ___________________
< can ducks use it? >
 -------------------
 \
  \
   \ >()_
      (__)__ _
```

**Comment by vcokltfre** [comment]
> You'll have to deliver the carrier pigeons, then, or they won't fly to you and I'll be stuck with an obscene amount of carrier pigeons and their produce.

I'm afraid this won't work as the business customer must arrange all shipping of payment. You will need to come to my location with approximately 90 million carrier pigeons for a few weeks before returning to the location of the Monopoly money to send with the pigeons.

> Like James and the Giant Peach?

Precisely

> How do you suggest I prevent it from evaporating in the strong wind? You probably have more experience with this than I do.

You must remove the wind.

**Comment by PH-KDX** [comment]
> You will need to come to my location with approximately 90 million carrier pigeons for a few weeks before returning to the location of the Monopoly money to send with the pigeons.

Fair enough. Please arrange for storage, food and permits.
> You must remove the wind.

Do you happen do have a spare nuclear reactor to power the windmills on the English coast? I'm considering turning them electrically to counteract the wind force.

**Comment by vcokltfre** [comment]
> Fair enough. Please arrange for storage, food and permits.

As mentioned the business customer must arrange the shipping and its costs.

> Do you happen to have a spare nuclear reactor to power the windmills on the English coast? I'm considering turning them electrically to counteract the wind force.

Unfortunately, I do not currently possess ownership of a nuclear reactor. What I would suggest is delivering the soul after the Monopoly money so that you can use the pigeons to counteract the wind by flapping their wings in the correct direction.

**Comment by PH-KDX** [comment]
> What I would suggest is delivering the soul after the Monopoly money so that you can use the pigeons to counteract the wind by flapping their wings in the correct direction.

now you're talking.
Wait, I just had an idea. How about a international sport event where the entire world's population obtains and trains, then flies their carrier pigeon from the Netherlands to the UK? Their identification badge could then contain one Monopoly bill...
As for the seagulls, it's simple. They're always flying around the ferries. Simply plaster the statues with scraps of food, and it'll be in the UK in no time.
I think I have enough info for now. I'll contact you privately once I have everything arranged. Thanks for all the help!
